[colors]
ansi = [
    '#0d0f13',
    '#f58c81',
    '#54c794',
    '#a9b852',
    '#6eb2fd',
    '#e58cc5',
    '#00c4d7',
    '#fffdfb',
]
background = '#181B1F'
brights = [
    # '#cc94e6',
    '#636363',
    '#f58c81',
    '#54c794',
    '#a9b852',
    '#6eb2fd',
    '#e58cc5',
    '#00c4d7',
    '#fffdfb',
]
cursor_bg = "#E09F47"
cursor_border = "#E09F47"
cursor_fg = '#0d0f13'
foreground = '#dedede'
selection_bg = '#3E4044'
# selection_fg = '#0d0f13'

[colors.indexed]

[colors.tab_bar]
background = '#0D0F13'

[colors.tab_bar.active_tab]
bg_color = '#0D0F13'
fg_color = '#DEDEDE'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#0D0F13'
fg_color = '#636363'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#0D0F13'
fg_color = '#636363'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = "#E09F47"
fg_color = "#636363"
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'


[metadata]
name = 'halloween_dark_hard'
